### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by corytortoise** [corytortoise/DuelsPE#2]
Here I will keep track of what is finished, and what is still to be added. This can give you an idea of the progress on this plugin.

 - [ ] Complete all timers and tasks
 - [ ] Complete EventListener
 - [ ] Complete Events and main API methods
 - [ ] Complete the plugin!
 - [ ] Multi Kit support
 - [ ] Multi Language support
 - [ ] Fully Document API

**Comment by uselesswaifu** [comment]
@corytortoise I'm not a Pro dev But I'll try to Complete the Timers and Task today and Maybe you can clean them up ;D

**Comment by uselesswaifu** [comment]
I wanted to Test and see what works but it wouldn't start due to Errors :P I'll fix that

**Comment by corytortoise** [comment]
That's because it's nowhere near finished.

**Comment by uselesswaifu** [comment]
Have a Mindset that it is finish ;)

**Comment by Tolo0** [comment]
Is this plugin finished? i get this error 

thread/CRITICAL]: ClassNotFoundException: "Class corytortoise\DuelsPE\C not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by corytortoise** [comment]
The README says the plugin is unfinished, and I'll update the progress tracker as needed. This error does need to be resolved though, so I'll fix it soon.

**Comment by Tolo0** [comment]
Ok thank you. i read the comment above and thought maybe it was finished but the Read me wasn't updated. i look forward to trying your plugin out. keep up the good work 😉

**Comment by TechnobladeYt** [comment]
New error found it says 
Error: "Cannot use object pocketmine\utils\Config as array" (EXCEPTION) in DuelsPE-master.phar/src/corytortoise/DuelsPE/Main" at line 89
